### PR TITLE
docs: improving IPv6 address consistency

### PR DESCRIPTION
**Pull request by MalteJ**
I have put the hosts into the `2001:db8:0::/64` subnet and hostX's containers into `2001:db8:x::/64` throughout the whole IPv6 documentation.
How do you like this?
I have not changed the routed network environment as it differs a bit from the others. Here the host's IPv6 address and its containers' addresses are in the same /64 subnet.

### CODE REVIEW

**Comment by estesp** [comment]
Hey, in general this looks good, but I think it conflicts with what I had done yesterday just before you created this--I had taken the switched example and updated both the diagram and text with basically the same ranges you are using here.  If you can update yours based on mine then I will pull this in and update the PR.

Thanks!

**Comment by MalteJ** [comment]
uhm, I thought I am doing this by sending a Pull Request to merge into your Pull Request?

**Comment by MalteJ** [comment]
the target of this PR is `estesp:10701-update-ipv6-docs` which should be the branch of your PR to `docker:master`

**Comment by estesp** [comment]
Sorry--when I had first looked at it given the timing I thought my update was conflicting with your PR to my branch.  I didn't realize you had actually pulled my latest update and then made changes on top of that.  I've been in all-day meetings the past 2 days, so sorry for the slow activity; I have merged this and updated the docker PR with the changes.

**Comment by MalteJ** [comment]
no problem :smiley:

**Pull request merged**
